### ISSUE TITLE
"DIRECTION" missing in BGC_schema

### ISSUE THREAD

**Issue by gmaze** [boom-lab/argo2parquet-public#3]
Hi,
I noticed that the "DIRECTION" variable is missing from the BGC schema
Was it done on purpose ?
If not, it would be usefull to have this variable as well in the parquet file
Otherwise, should we assume profiles are only from ascent direction ?

**Comment by enrico-mi** [comment]
Hi @gmaze, it's not in there by design - our original goal was to create an edited database for users who don't need such information, and in adapting the code for the Argo working group I have kept the schema of that use case. So as of now both directions are included but not specified in any parameter. I'm happy to include it for the working group.

**Comment by gmaze** [comment]
Awesome, that indeed would help me to integrate this within argopy

**Comment by enrico-mi** [comment]
Added.
